# Generated by Django 5.1.7 on 2026-07-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_trigger_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='trigger_type',
            field=models.CharField(choices=[('renewal_remind', 'Renewal Reminder'), ('renewal_confirm', 'Renewal Confirmed'), ('enrollment', 'New Enrollment'), ('expiry', 'Membership Expired'), ('manual', 'Manual'), ('enquiry_welcome', 'Enquiry Welcome'), ('enquiry_followup', 'Enquiry Follow-up'), ('absent', 'Member Absent'), ('staff_absent', 'Staff Absent'), ('new_plan', 'New Plan Announcement'), ('diet_reminder', 'Diet Reminder'), ('pending_payment_member', 'Pending Payment Reminder'), ('pending_payment_admin', 'Pending Payment Summary (Admin)'), ('balance', 'Balance Payment Bill'), ('pt_renewal', 'PT Renewal Bill'), ('pt_balance', 'PT Balance Payment Bill')], db_index=True, default='manual', max_length=30),
        ),
    ]
