# Generated by Django 5.1.7 on 2026-08-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='trigger_type',
            field=models.CharField(choices=[('renewal_remind', 'Renewal Reminder'), ('renewal_confirm', 'Renewal Confirmed'), ('enrollment', 'New Enrollment'), ('expiry', 'Membership Expired'), ('manual', 'Manual'), ('enquiry_welcome', 'Enquiry Welcome'), ('enquiry_followup', 'Enquiry Follow-up'), ('absent', 'Member Absent'), ('staff_absent', 'Staff Absent'), ('member_checkin', 'Member Check-in'), ('staff_checkin', 'Staff Check-in'), ('new_plan', 'New Plan Announcement'), ('diet_reminder', 'Diet Reminder'), ('pending_payment_member', 'Pending Payment Reminder'), ('pending_payment_admin', 'Pending Payment Summary (Admin)'), ('balance', 'Balance Payment Bill'), ('pt_renewal', 'PT Renewal Bill'), ('pt_balance', 'PT Balance Payment Bill')], db_index=True, default='manual', max_length=30),
        ),
    ]
