# Generated by Django 5.1.7 on 2026-08-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_alter_notification_trigger_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('chrome', 'Chrome Push')], default='whatsapp', max_length=10),
        ),
    ]
