# Generated by Django 5.1.7 on 2026-07-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_member_notifications_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='renewal_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], db_index=True, default='active', max_length=12),
        ),
        migrations.AlterField(
            model_name='memberpayment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('pending', 'Pending')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='trainerassignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
