# Generated by Django 5.1.7 on 2026-07-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('followup', 'Follow-up'), ('converted', 'Converted'), ('lost', 'Lost')], db_index=True, default='new', max_length=20),
        ),
        migrations.AddIndex(
            model_name='enquiryfollowup',
            index=models.Index(fields=['scheduled_date', 'sent'], name='enquiries_e_schedul_d2e22f_idx'),
        ),
    ]
